### ISSUE TITLE
Notice about your fork of Catalyst

### ISSUE THREAD

**Issue by jdev082** [TechStudent10/SquidBOT#3]
Hello, @TechStudent10. I am reaching out to inform you of the Catalyst fork requirements.

I kindly ask that you do the following to your Catalyst fork:

- Enable Issues (unless it's a fork to make changes to the mainstream Catalyst)
- Rename and rebrand (unless it's a fork to make changes to the mainstream Catalyst)

*After this, a guide will appear in the Issues tab of your Catalyst fork, linking the developer documentation as well as what file does what and the way around the code.*

**Comment by TechStudent10** [comment]
Hello Jayden. I am just making a fork to make some changes to the README.
